services:
  - type: web
    name: cs2-market-full
    env: node
    plan: free
    buildCommand: |
      cd frontend && npm install && npm run build
      cd ../backend && npm install
    startCommand: node backend/index.js
    envVars:
      - key: NODE_VERSION
        value: 18
    staticPublishPath: frontend/build
